# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_upload_alt'),
        ('news', '0002_auto_20150723_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
    ]
