# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('union_phone', models.CharField(max_length=10)),
                ('student_counselor_dtek', models.CharField(max_length=10)),
                ('curator', models.CharField(max_length=10)),
                ('chalmers_ward', models.CharField(max_length=10)),
                ('healthcare_info', models.CharField(max_length=10)),
                ('emergency_info', models.CharField(max_length=10)),
            ],
        ),
    ]
