# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20150804_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(upload_to=upload.models.setFilePath),
        ),
    ]
