# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='alt',
            field=models.TextField(blank=True),
        ),
    ]
