# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20150723_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='image',
            field=models.FileField(blank=True, upload_to='%Y'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.FileField(blank=True, upload_to='%Y'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
