# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20160723_1252'),
        ('about', '0004_auto_20160723_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.Upload'),
        ),
        migrations.AddField(
            model_name='member',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.Upload'),
        ),
    ]
