# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160723_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
    ]
