# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
