# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_widget_url', models.TextField()),
                ('twitter_widget_id', models.TextField()),
                ('gcal_api_key', models.TextField()),
                ('gcal_dnollk_calendar_id', models.TextField()),
                ('gcal_dnollk_calendar_url', models.TextField()),
                ('gcal_timeedit_calendar_id', models.TextField()),
                ('gcal_asp_calendar_id', models.TextField()),
                ('enable_dnollk_calendar', models.BooleanField()),
                ('enable_timeedit_calendar', models.BooleanField()),
                ('enable_asp_calendar', models.BooleanField()),
                ('gform_link', models.TextField()),
                ('gform_embed_link', models.TextField()),
                ('enable_form', models.BooleanField()),
            ],
        ),
    ]
