# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnollkse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='config',
            name='enable_asp_calendar',
        ),
        migrations.RemoveField(
            model_name='config',
            name='enable_dnollk_calendar',
        ),
        migrations.RemoveField(
            model_name='config',
            name='enable_timeedit_calendar',
        ),
        migrations.AddField(
            model_name='config',
            name='favicon_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='header_url',
            field=models.TextField(default='/static/dnollkse/images/header.jpg'),
        ),
        migrations.AddField(
            model_name='config',
            name='logo_url',
            field=models.TextField(default='/static/dnollkse/images/logo.png'),
        ),
        migrations.AddField(
            model_name='config',
            name='year',
            field=models.CharField(default='2017', max_length=4),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_api_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_asp_calendar_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_dnollk_calendar_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_dnollk_calendar_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_timeedit_calendar_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gform_embed_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gform_link',
            field=models.TextField(null=True),
        ),
    ]
