# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnollkse', '0002_auto_20170715_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
