# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnollkse', '0003_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='favicon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_asp_calendar_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_dnollk_calendar_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_dnollk_calendar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gcal_timeedit_calendar_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gform_embed_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='gform_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
